import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import Navigation from './Components/Navigation';
import Footer from './Components/Footer';
import { GlobalContextProvider } from './context/context';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });
const monst = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lifestyle Medly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monst.className}>
        <GlobalContextProvider>
          <Navigation />
            {children}
          <Footer />
        </GlobalContextProvider>
        <Script type="text/javascript">
          window.klaraWidget = window.klaraWidget || [];
          window.klaraWidget.push(["setWidgetId", "e9800103-4073-4ccb-871b-c21daaf2448d"]);
        </Script>

        <Script type="text/javascript" src="https://s3.amazonaws.com/widget-frontend.klara.com/bundle.js"> </Script>
      </body>
    </html>
  )
}
