import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import Navigation from './Components/Navigation';
import Footer from './Components/Footer';
import { GlobalContextProvider } from './context/context';

const inter = Inter({ subsets: ['latin'] });
const monst = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lifestyle Medly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monst.className}>
        <GlobalContextProvider>
          <Navigation />
            {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  )
}
