import Link from "next/link";

export default function TermsOfServices() {
    return (
        <div className='w-full pt-10 pb-20 px-10'>
            <div className='max-w-[600px] mx-auto text-charcoal'>
                <span className="inline-block mb-10"><Link href='/' className='text-maize'>Home</Link> / Terms Of Service</span>
                <p className='text-[28px] font-semibold mb-5'>Lifestyle Medly LLC Terms of Use</p>
                <p className='font-semibold mb-5'>This document contains the terms and conditions of using the Lifestyle Medly website and services.</p>
                <p className='mb-5'>Effective January 29, 2024</p>
                <p className='mb-5'>Lifestyle Medly Terms</p>
                <p className='mb-5'>Last Updated: January 29, 2024</p>
                <p className='mb-5'>Your use of www.lifestylemedly.com, chatbot function, and services, both online and offline provided by or through Lifestyle Medly LLC (“Lifestyle Medly”, “we”, “us” or “our”) that link to or utilize our websites, applications, and services (the “Website and Services”) is governed by these terms and conditions of Website and Services use ("Terms and Conditions"). Your use of the Website and Services and your participation in any health and/or wellness program accessible through or a part of the Website and Services may be subject to additional policies, rules, consent forms, statements of rights, and/or conditions ("Additional Terms"). These Additional Terms are incorporated herein by reference, and by accessing or using any aspect of the Website and Services, you agree to also comply with the Additional Terms. In the event of a conflict between these Terms and Conditions and any supplemental terms provided as part of the Additional Terms for a specific portion of the Website and Services, such supplemental terms of the Additional Terms shall control with respect to your use of that specific portion of the Services.</p>
                <p className='font-semibold mb-5'>Please read these Terms and Conditions carefully and in their entirety before using the Website and Services. </p>
                <p className='mb-5'>By accessing or using the Lifestyle Medly Website and Services, you are acknowledging that you are over eighteen (18) years of age, that you have read, understand, and agree to be bound by these Terms and Conditions, and that you have read and understood the terms and conditions of Lifestyle Medly's Privacy Policy.  Lifestyle Medly provides the Website and Services to supply general information about Lifestyle Medly and its products and services, including online telehealth medical consultations and secure messaging between Lifestyle Medly service providers, other healthcare professionals, and you, their patients. You may use this Website and Services subject to your compliance with these terms and conditions, and your accessing and using the Website and Services evidence your express agreement to follow and to be bound by these Terms and Conditions. If you disagree with these Terms and Conditions, do not use this Website and Services.</p>
                
                <p className='font-semibold mb-5'>Privacy Policy.</p>
                <p className='mb-5'>Lifestyle Medly is committed to respecting the personal privacy of the individuals who use this Website and Services. The Privacy Policy posted on this Website describes Lifestyle Medly's current policies and practices regarding the personal information collected by Lifestyle Medly through this Website and Services. The Privacy Policy is part of these Terms and Conditions. When you agree to be bound by these Terms and Conditions, you are consenting to the collection, use, and disclosure of your personal information in accordance with the Privacy Policy on this Website and Services. Please take a few minutes to review this policy, which can be found here.</p>
                <p className='mb-5 font-semibold'>Registration, and security.</p>
                <p className='mb-5'>You are entirely responsible for providing us with accurate, complete, and updated user registration information about yourself. You represent and warrant that you are an individual of legal age to enter into a binding contract in your state of residence. If you are using or participating on the Website and Services as a personal representative of another person, such as a person’s parent, guardian, conservator, or custodian (“Family Member”), you also represent and warrant that you have the appropriate legal authority to provide and do consent to act on behalf of any Family Member. In that capacity, you further agree to the Terms and Conditions and Privacy Policy, and provide consent for the treatment of the Family Member.</p> 
                <p className='mb-5'>You may only use the Services for your or a Family Member’s internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws and regulations applicable to you. Lifestyle Medly operates subject to state and federal laws and regulations, and some Services may not be available in your state or country. You represent that you or the Family Member are not barred from enrolling for and/or receiving the Services under the laws or regulations of the United States or other applicable jurisdictions. Access to and use of the Services is limited exclusively to users located in states within the United States where the Services are available and in which Lifestyle Medly is transacting business. Accessing the Services from jurisdictions where content is illegal or where Lifestyle Medly does not offer Services is prohibited. If your use of the Services is prohibited by applicable laws, then you are not authorized to use the Services. Lifestyle Medly will not be responsible for your use of the Services in a way that violates any federal or state law or regulation.</p>
                <p className='font-semibold mb-5'>User Registration Information.</p>
                <p className='mb-5'>You must notify Lifestyle Medly promptly if any of the information you provided as part of any user registration process changes or if you become aware that any of the user registration information is inaccurate or incomplete. Such notification must detail the changes in such information. Lifestyle Medly has the right to rely on the most recent user registration information unless and until you provide updated user registration information. You agree that Lifestyle Medly may provide notices and updates to these Terms and Conditions, our Privacy Policy or to this Website and Services either by posting updates on our website, or by email using the address maintained with Lifestyle Medly.</p>
                <p className='font-semibold mb-5'>Right to Change Website and Services.</p>
                <p className='mb-5'>Lifestyle Medly reserves the right to modify the content and functionality of this Website and Services, limit access to this Website and Services, or shut down this Website and suspend or terminate Services temporarily or permanently, at any time, for any reason, and without prior notice. Lifestyle Medly will not be liable to you or your company for possible consequences of such changes, suspension, termination or shutdown.</p>
                <p className='font-semibold mb-5'>Programs and Services.</p>
                <p className='mb-5'>Health care professionals (“Providers”) employed or contracted by Lifestyle Medly may use the Website to provide and coordinate access to certain health care services to you. You may use the Services to connect via telehealth with Providers or to access other Lifestyle Medly Services. Providers provide medical services on behalf of Lifestyle Medly, and each Provider exercises independent medical judgment in the delivery of care or advice. </p>
                <p className='mb-5 font-semibold'>LIFESTYLE MEDLY DOES NOT CONTROL OR DIRECT THE MEANS, METHODS, OR MANNER BY WHICH ANY PROVIDER EXERCISES PROFESSIONAL JUDGMENT IN CONNECTION WITH THE PROVISION OF SERVICES. THE SERVICES ARE NOT, AND SHOULD NEVER BE USED AS, A SUBSTITUTE FOR EMERGENCY MEDICAL CARE. IF YOU HAVE A MEDICAL OR MENTAL HEALTH EMERGENCY, ARE THINKING ABOUT SUICIDE, OR TAKING ACTIONS THAT MAY CAUSE HARM TO YOU OR OTHERS, SEEK EMERGENCY TREATMENT AT THE NEAREST EMERGENCY ROOM OR DIAL 911.</p>
                <p className='mb-5'>Providers may prescribe medications available from pharmacies not listed on the Lifestyle Medly website. In such cases, you may incur additional costs related to such prescriptions.</p>
                <p className='mb-5'>The Services may include the provision of telehealth services by a Provider. Telehealth involves the delivery of health care services using electronic communications, information technology, or other means between a health care provider and a patient who are not in the same physical location. Providers may also rely on information and materials you provide through the Services, including information and materials you may have received from your other health care providers. It is your sole responsibility to provide accurate information to a Provider.</p>
                <p className='mb-5 font-semibold'>Website Security.</p>
                <p className='mb-5'>This section of our Terms and Conditions is dedicated to addressing the security measures we employ, and the inherent risks associated with using the internet. By accessing or using our services, you acknowledge and agree to these terms.</p>
                <p className='mb-5 font-semibold'>Our Commitment to Security.</p>
                <p className='mb-5'>We are committed to protecting the security of your data and our services. We employ a range of technical, administrative, and physical measures designed to protect the confidentiality, integrity, and availability of the information you provide to us (“Security Policy”). </p>

                <p className='mb-5 font-semibold'>Your Responsibility.</p>
                <p className='mb-5'>While we strive to use commercially acceptable means to protect your information, no method of transmission over the internet or method of electronic storage is 100% secure. Therefore, we cannot guarantee its absolute security.</p>
                <p className='mb-5'><span className='font-semibold'>a. Account Security:</span> You are responsible for safeguarding the password that you use to access our services and for any activities or actions under your password. We encourage you to use “strong” passwords (passwords that use a combination of upper- and lower-case letters, numbers, and symbols) to protect your account.</p>
                <p className='mb-5'><span className='font-semibold'>b. Data Security:</span> You are responsible for maintaining the security of your own data that you transmit through our services. You should be aware of the risks of transmitting personal or confidential information over the internet.</p>
                <p className='mb-5 font-semibold'>Inherent Risks of the Internet.</p>
                <p className='mb-5'>You acknowledge that there are certain inherent risks in using the internet. These risks include, but are not limited to:</p>
                <p className='mb-5'><span className='font-semibold'>a. Interception of Data:</span> Transmission of data over the internet may be subject to interception by unauthorized third parties.</p>
                <p className='mb-5'><span className='font-semibold'>b. Malware:</span> The risk of inadvertently downloading software or files that may contain viruses, spyware, or other harmful components.</p>
                <p className='mb-5'><span className='font-semibold'>c. Phishing and Spoofing:</span> The risk of encountering fraudulent attempts to collect your personal information or illegitimately represent our services.</p>
                <p className='mb-5 font-semibold'>Notification of Security Breaches.</p>
                <p className='mb-5'>In the unfortunate event of a security breach that affects your data, we will notify you as soon as possible in accordance with applicable laws and regulations.</p>
                <p className='mb-5 font-semibold'>Changes to Our Security Policy.</p>
                <p className='mb-5'>We may update our Security Policy to reflect changes to our information practices or to reflect our legal obligations. If we make any material changes, we will notify you by email (sent to the e-mail address specified in your account) or by means of a notice on this website prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our security practices.</p>

                <p className='mb-5 font-semibold'>Prescription Policy.</p>
                <p className='mb-5'>Lifestyle Medly does not endorse any specific pharmacy, or pharmacologic product. If a Provider prescribes a medication, he/she will do so at their discretion and professional judgment. There is no guarantee a prescription will be written. Providers do not prescribe DEA controlled substances or scheduled medications or certain other drugs that may be harmful due to their potential for abuse. Providers reserve the right to deny care for actual or potential misuse of the Services. Lifestyle Medly and its Providers fully honor patient freedom of choice, and if you receive a prescription for a medication, you always have the option to instruct Lifestyle Medly and/or the Provider to transmit that prescription to the pharmacy of your choice.</p>
                <p className='mb-5 font-semibold'>Communications by Text Message and Email.</p> 
                <p className='mb-5'>Registering with Lifestyle Medly, you expressly consent and opt-in to receive text (SMS) messages from Lifestyle Medly regarding your account and use of the Services. These text messages may include order confirmations, shipping notifications, messages from your healthcare provider, and other transactional messages, as well as promotional and marketing notifications from Lifestyle Medly, to the extent you have opted-in to receive such messages from Lifestyle Medly.</p>
                <p className='mb-5'>While Lifestyle Medly takes your privacy and the security of your health and other sensitive information seriously, the transmission of information over the internet and mobile networks is never 100% secure. Text messages and emails that you send to or receive from Lifestyle Medly may not be encrypted, which means that they may be intercepted by third parties. If you choose to send or receive information about your health or any other sensitive information by text message or email, you do so at your own risk.</p>
                <p className='mb-5 font-semibold'>User Information.</p>
                <p className='mb-5'>Anything you post, upload, share, store, or otherwise provide through the Website or Services, including text, photos, audio, code, instructions, requests, ideas, suggestions, comments, forms, and agreements, files, videos, images, and other materials is your “User Information.” You are solely responsible for all User Information you contribute to the Website or Services. You represent that all User Information submitted by you is accurate, complete, up-to-date, and in compliance with all applicable laws, rules, and regulations.</p>
                <p className='mb-5 font-semibold'>User Information Licenses.</p> 
                <p className='mb-5'>In order to display your User Information on the Website and Services and allow other users to use and access them, you grant Lifestyle Medly certain rights in your User Information. By submitting, posting, or displaying User Information through the Website and Services, and to the extent permitted by law, you grant Lifestyle Medly a perpetual, irrevocable, worldwide, royalty-free, fully paid, sublicensable, transferable, and non-exclusive license to use, reproduce, adapt, modify, aggregate, translate, publish, publicly perform, publicly display, distribute, edit, reformat, prepare derivative works of, and otherwise fully exploit such User Information in connection with the Website and Services and Lifestyle Medly’s businesses.</p>
                <p className='mb-5'>Copyright Notice and Limited License. Everything you see and hear on this Website and as part of the Services (the “Content”), including text, photographs, illustrations, graphics, audio clips, video clips, and audio-video clips, is protected by law, including copyrights and service marks. You are granted a limited, revocable, non-transferrable/non-sublicensable non-exclusive license to the Content subject to the following limitations:</p>
                <p className='mb-5'>You may download, store, print, copy, and share Content from this Website and Services for noncommercial with Lifestyle Medly.</p>
                <p className='mb-5'>You may publish or post any part of the Content on any other internet site or in any other media in a similar context to that in which it is presented on this Website and Services.</p>
                <p className='mb-5'>You may not modify or alter the Content in any way or delete or modify any copyright or trademark notices or notices of confidentiality.</p>
                <p className='mb-5'>Except as expressly stated above, you may not copy, download, print, publish, display, perform, distribute, transmit, transfer, translate, modify, add to, update, compile, abridge, or in any other way transform or adapt all or any part of the Content of this Website and Services without first obtaining written permission from Lifestyle Medly.</p>
                <p className='mb-5 font-semibold'>Intellectual Property and Trademark Notice.</p> 
                <p className='mb-5'>Lifestyle Medly, Lifestyle Medly has sole and exclusive ownership of all right, title, and interest in and to this Website and Services, including the design, features, functionality, navigation, Content, and "look and feel" of this Website and Services, and all data collected through this Website and Services, including all intellectual property rights associated therewith.</p>
                <p className='mb-5'>All trademarks, service marks, and logos displayed on this Website and Services (the “Trademarks”) are registered and unregistered trademarks of Lifestyle Medly, its affiliates, or third parties who have licensed their trademarks to Lifestyle Medly or its affiliates.</p>
                <p className='mb-5'>Except as expressly stated in these terms and conditions, you may not reproduce, display, or otherwise use, reprint, or publish text, images, graphics, or other Content of this Website and Services or any Trademark without first obtaining Lifestyle Medly's written permission. Any Content, information, or materials provided by Lifestyle Medly on this Website and Services are at the user/customer’s own risk, and each user/customer must review its own use of our products and services for suitability for the intended purpose or the necessity of obtaining any applicable intellectual property licenses.</p>


                <p className='mb-5 font-semibold'>Unsolicited Ideas.</p>
                <p className='mb-5'>Lifestyle Medly welcomes your comments and feedback regarding this Website and Services and our products.</p>
                <p className='mb-5'>By submitting communications and/or materials to Lifestyle Medly through this Website and Services, you assign to Lifestyle Medly, free of charge, all worldwide rights, title, and interest in all copyrights and other intellectual property rights in the information and/or materials you submit to Lifestyle Medly. Lifestyle Medly will be entitled to use any non-Personal Data (including de-identified Personal Data), and/or materials you submit through this Website and Services, and any ideas, concepts, know-how, or techniques contained in any such information and/or materials, for any purpose, including, but not limited to, developing, manufacturing, and marketing products using such information or materials without restriction and without compensating you.</p>  
                <p className='mb-5'>Lifestyle Medly will not use any information or materials you submit through this Website and Services in a way that may violate applicable privacy laws and regulations. In particular, Lifestyle Medly will not release your name or otherwise publicize the fact that you submitted information or materials to us unless we obtain your permission to use your name or are required to do so by law.</p>
                <p className='mb-5'>You are responsible for the content of any communications you submit through this Website and Services, including their truthfulness and accuracy. Please note that your submissions (e.g., via our contact form) do not have any legally binding effect on Lifestyle Medly.</p> 
                <p className='mb-5 font-semibold'>Third-Party Information.</p> 
                <p className='mb-5'>Some of the information, articles, and other materials available through this Website and Services are provided to Lifestyle Medly by third parties. The source of these third-party materials is identified where available. These third-party materials are provided for your interest and convenience only. Lifestyle Medly does not warrant or represent that these materials are current, accurate, complete, or reliable. Lifestyle Medly accepts no responsibility or liability for your access to or use of such third-party website and third-party website information.</p>
                <p className='mb-5 font-semibold'>Links to Other Lifestyle Medly Websites.</p>
                <p className='mb-5'>This Website and Services contain hyperlinks to other websites operated by Lifestyle Medly or other Lifestyle Medly entities ("Other Lifestyle Medly Website(s)"). Each of these Other Lifestyle Medly Websites is separate and governed by their respective terms of use and privacy policies. Please review the terms of use and privacy statement of each Other Lifestyle Medly Website(s) you visit.</p>
                <p className='mb-5 font-semibold'>Links to Third-Party Websites.</p>
                <p className='mb-5'>This Website and Services include hyperlinks to non-Lifestyle Medly operated websites for your convenience only. Lifestyle Medly does not endorse the content on these third-party websites and is not responsible for their contents. Access and use of these third-party websites are at your own risk.</p>
                <p className='mb-5 font-semibold'>Product and Services Information.</p>
                <p className='mb-5'>Information on this Website and Services serves as an introduction to Lifestyle Medly and its products and services. For specific advice related to our products and services, please contact Lifestyle Medly directly at [INSERT LINK].com. Users intending to use Lifestyle Medly products or services must comply with all applicable laws and regulations.</p>
                <p className='mb-5 font-semibold'>Disclaimer of Warranties.</p>
                <p className='mb-5 font-semibold'>LIFESTYLE MEDLY, PROVIDERS, AND THEIR RESPECTIVE PARTIES MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THE SERVICES, INCLUDING THE ACCURACY, LEGALITY, OR DECENCY OF CONTENT, EXPRESSED OR IMPLIED. THE SERVICES AND CONTENT ARE PROVIDED ON AN "AS-IS" AND "AS AVAILABLE" BASIS, AND SUBJECT TO ALL FLAWS, WITHOUT WARRANTIES OF ANY KIND. USERS ACKNOWLEDGE AND AGREE THAT THEIR USE OF THE SERVICES IS AT THEIR SOLE RISK. LIFESTYLE MEDLY MAKES NO REPRESENTATION, WARRANTY, PROMISE, OR GUARANTY THAT THE WEBSITE WILL BE AVAILABLE OR FULLY OPERATIVE AT ANY TIME OR ON AN UNINTERRUPTED OR ERROR-FREE BASIS. THE WEBSITE MAY CONTAIN ERRORS, GLITCHES, BUGS, OR OTHER DEFECTS, AND YOU UNDERSTAND AND ACKOWLEDGE THAT YOUR EXCLUSIVE RIGHT AND REMEDY IN THE EVENT OF YOUR DISSATISFACTION WITH THE WEBSITE IS FOR YOU TO NOTIFY US ABOUT THE DISSATISFACTION WITH THE WEBSITE, IN WHICH CASE WE WILL REVIEW THE COMPLAINT, AND/OR TO STOP USING THE WEBSITE</p>
                <p className='mb-5 font-semibold'>Global Availability.</p>
                <p className='mb-5'>Products, programs, or services referenced on this Website and Services may not be available in all countries. References to Lifestyle Medly products, programs, and services do not imply availability in your country. For information on availability, contact your local Lifestyle Medly representative.</p>
                <p className='mb-5 font-semibold'>Contact Us.</p>
                <p className='mb-5'>The Lifestyle Medly Chatbot ("Chatbot") feature allows you to send questions to our team via email. We use your information primarily for service delivery, offers, and notifications. Chatbot responses are not Telehealth Services, nor are they a substitute for Telehealth Services, which must be provided to you by a Provider.</p>
                <p className='mb-5 font-semibold'>Indemnification.</p>
                <p className='mb-5'>You agree to indemnify Lifestyle Medly from claims, actions, proceedings, investigations, allegations, or complaints arising from your use of the Website and/or Services, violation of Terms, and content provided. To the fullest extent permitted by law, Lifestyle Medly, LLC and its employees, contractors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages, including, but not limited to, damages for lost profits, loss of data, or loss of goodwill, arising out of or in connection with the use of Website or the Telehealth Services.</p>
                <p className='mb-5 font-semibold'>Governing Law and Jurisdiction.</p>
                <p className='mb-5'>The laws of the United States and the State of New Jersey govern these Terms and Conditions. Legal actions related to this Website and Services shall be brought exclusively in a state court in New Jersey.</p>
                <p className='mb-5 font-semibold'>JURY WAIVER, ARBITRATION, CLASS ACTION WAIVER.</p>
                <p className='mb-5 font-semibold'>a. Agreement to Arbitrate</p>
                <p className='mb-5'>You and Lifestyle Medly agree that any dispute, claim, or controversy arising out of or relating to your use of our services, or the breach, termination, enforcement, interpretation, or validity of these Terms and Conditions or this Agreement, shall be resolved by binding arbitration, rather than in court, except that you may assert claims in small claims court if your claims qualify.</p>
                <p className='mb-5 font-semibold'>b. Waiver of Jury Trial</p>
                <p className='mb-5 font-semibold'>YOU AND LIFESTYLE MEDLY HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY.</p> 
                <p className='mb-5'>You and Lifestyle Medly are instead electing that all claims and disputes shall be resolved by arbitration under this Agreement, except for matters that qualify for small claims court jurisdiction. An arbitrator can award on an individual basis the same damages and relief as a court and must follow this Agreement as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</p>
                <p className='mb-5 font-semibold'>c. Class Action and Mass Arbitration Waiver</p>
                <p className='mb-5 font-semibold'>YOU AND LIFESTYLE MEDLY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</p>
                <p className='mb-5'>Further, unless both you and Lifestyle Medly agree otherwise, the arbitrator may not consolidate more than one person's claims and may not otherwise preside over any form of a representative or class proceeding.</p>
                <p className='mb-5 font-semibold'>Modifications to this Agreement.</p>
                <p className='mb-5'>Notwithstanding any provision in the Terms of Service to the contrary, you and we agree that if Lifestyle Medly makes any future change to this arbitration agreement (other than a change to the Lifestyle Medly’s address for Notice), you may reject any such change by sending us written notice within 30 days of the change to the Lifestyle Medly's address for Notice. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Agreement.</p>
                <p className='mb-5 font-semibold'>Severability.</p>
                <p className='mb-5'>If a court decides that any part of this Agreement is invalid or unenforceable, the other parts of this Agreement will still apply.</p>
                <p className='mb-5 font-semibold'>Waiver.</p>
                <p className='mb-5'>Failure to enforce any provision or right under these terms at any time does not constitute a waiver. All waivers must be in writing and signed.</p>
                <p className='mb-5 font-semibold'>Severability.</p>
                <p className='mb-5'>If any provision is deemed contrary to law, it shall be changed to fulfill the original objectives. Remaining provisions shall remain in full force.</p>
                <p className='mb-5 font-semibold'>Notice.</p>
                <p className='mb-5'>Manner of Notice. Any notice, request, demand, consent, or other communication required or permitted under this Agreement shall be in writing and shall be deemed to have been duly given on the date of service if served personally on the party to whom notice is to be given, or on the third day after mailing if mailed to the party to whom notice is to be given, by first class mail, registered or certified, postage prepaid, and properly addressed as follows:</p>
                <p className='font-semibold'>To Lifestyle Medly, LLC</p>
                <p>441 US Highway 130</p> 
                <p>East Windsor, NJ 08520</p>
                <p className='mb-5'>Attn: Hassan Shahid, MD</p>

                <p className='mb-5'>With a copy to:</p>
                <p className="font-semibold">Mandelbaum Barrett, PC</p>
                <p>3 Becker Farm, Suite 105</p>
                <p>Roseland, New Jersey 07068</p>
                <p className='mb-5'>Attention: Mohamed Nabulsi, Esquire</p>


                <p className='mb-5 font-semibold'>Entire Agreement.</p>
                <p className='mb-5'>These terms constitute the entire agreement between the user and Lifestyle Medly regarding access to and use of this Website and Services.</p>
                <p className='mb-5 font-semibold'>Changes to Terms and Conditions.</p>
                <p className='mb-5'>Lifestyle Medly reserves the right to update these terms and conditions at any time without prior notice. Users agree to follow the revised terms by using the Website and Services after changes.</p>











	


                
                {/* <p className='font-semibold mb-5'>Privacy Policy.</p>

                <p className='font-semibold mb-5'>Registration, and security.</p>

                <p className='font-semibold mb-5'>User Registration Information.</p>

                <p className='font-semibold mb-5'>Right to Change Website and Services.</p>

                <p className='font-semibold mb-5'>Programs and Services.</p> */}


            </div> 
        </div>
    )
}